name: GitHub Classroom Workflow

on: workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: education/autograding@v1
     
